### ISSUE TITLE
using @ in place of HEAD

### ISSUE THREAD

**Issue by pho3nixf1re** [knu/zsh-git-escape-magic#1]
This does not work when using the @ shortcut for HEAD. Example:

This is what is typed and is ignored my git-escape-magic.

```
git reset @^
```

The expected behavior would have the output

```
git reset @\^
```

but this does not happen.

Using HEAD works fine:

```
git reset HEAD\^
```

**Comment by knu** [comment]
Sorry for the late fix!

**Comment by pho3nixf1re** [comment]
Thanks for this! I updated my PR to robbyrussell/oh-my-zsh . This will come it handy!
